### ISSUE TITLE
At time of decoding always blackhhole

### ISSUE THREAD

**Issue by paula-em-lafon** [smbwain/signed#2]
Hello.

I've been trying to set up this package so I can sign some files and I'm having a bit of trouble with it because whenever I try to verify a signed url it returns blackholed. I've made a stackoverflow issue. Thanks for your attention :)

[stackoverflow link](https://stackoverflow.com/questions/56331185/cant-get-signed-url-to-not-blackhole)

**Comment by smbwain** [comment]
Probably it's related to bug fixed here: https://github.com/smbwain/signed/pull/1.
Update to signed:1.0.1 and let me know

**Comment by smbwain** [comment]
I'm closing it. Feel free to reopen if problem still exists.
