### ISSUE TITLE
What does the blackholed url mean?

### ISSUE THREAD

**Issue by bionner** [smbwain/signed#7]
Hi, i created some links with your package, at the beginning they were working, but i did some changes and then they got broke. All links enter on the blackholed callback, there is a way to know what error is throwing or do you know what is ?

**Comment by anniestudent** [comment]
For me, it was the unmatched protocol causing the blackhole issue. I signed with https:// but the req.protocol is http://.

**Comment by smbwain** [comment]
Blackholed means that signature doesn't match the url. Unfortunately, there is no easy way to say what exactly wrong. Different protocol or port can be the reason.
