### ISSUE TITLE
Would be more useful if Express (version) dependency was removed

### ISSUE THREAD

**Issue by tohagan** [smbwain/signed#8]
Thanks this is a very useful lib for creating download URLs requiring credentials. Though I'm wishing it only performed the `sign()` and `verify()` parts so it could be more radiality re-used in any NodeJS stack.  I think that having a specific ExpressJS version dependency means you might end up loading up a couple of versions of Express so it's no longer 'tiny'. I wanted to use it in a Firebase service but will need to fork I suspect.

I wonder if you just wrote a function that performed everything that the middleware does but removed the ExpressJS types. You could then just include a tiny code sample showing how to wrapper this function to create the middleware function for Express.  Then anyone can do this same for their Express-alternative stack.

**Comment by smbwain** [comment]
Thank you
Now new version of library has been pushed. Although there is still ready to go express middleware, there is also _verify_ method, which can be used without express.
ExpressJS dependency shouldn't be an issue, as it's only @types/express dependency. Not entire expressJS.
Feel free to reopen this if you think there is still an issue to use it without express.
