### ISSUE TITLE
MD5?

### ISSUE THREAD

**Issue by gugu** [smbwain/signed#9]
This module uses md5 internally. MD5 should not be used currently at all, especially for security-related things. Any plan to use SHA512?

**Comment by elleryfamilia** [comment]
Good observation. Any thoughts on good alternatives? Crypto.js?

**Comment by elleryfamilia** [comment]
> This module uses md5 internally. MD5 should not be used currently at all, especially for security-related things. Any plan to use SHA512?



> This module uses md5 internally. MD5 should not be used currently at all, especially for security-related things. Any plan to use SHA512?

Good observation. Any thoughts on good alternatives? Crypto.js?

**Comment by smbwain** [comment]
New version of library uses sha1 by default. But you can also configure it to use any other method, including custom hashing function.
